import { ExpenseCategory } from "./types";

export const CATEGORY_META: Record<
  ExpenseCategory,
  { emoji: string; keywords: string[] }
> = {
  餐飲: {
    emoji: "🍔",
    keywords: [
      "餐",
      "飯",
      "食",
      "吃",
      "喝",
      "cafe",
      "coffee",
      "starbucks",
      "restaurant",
      "diner",
      "grill",
      "burger",
      "pizza",
      "taco",
      "brunch",
      "groceries",
      "grocery",
      "market",
      "trader joe",
      "whole foods",
      "walmart",
      "costco",
      "in-n-out",
      "mcdonald",
      "chipotle",
      "subway sandwich",
      "lunch",
      "dinner",
      "breakfast",
      "咖啡",
      "午餐",
      "晚餐",
      "早餐",
      "超市",
      "雜貨",
    ],
  },
  交通: {
    emoji: "🚗",
    keywords: [
      "交通",
      "車",
      "油",
      "加油",
      "gas",
      "gasoline",
      "fuel",
      "shell",
      "chevron",
      "rental",
      "rental car",
      "avis",
      "hertz",
      "enterprise",
      "uber",
      "lyft",
      "waymo",
      "bart",
      "muni",
      "caltrain",
      "parking",
      "toll",
      "flight",
      "airline",
      "alaska air",
      "delta",
      "united",
      "租車",
      "停車",
      "機票",
      "國內線",
    ],
  },
  購物: {
    emoji: "🛍️",
    keywords: [
      "購物",
      "買",
      "shop",
      "store",
      "mall",
      "outlet",
      "premium outlet",
      "desert hills",
      "apple store",
      "nike",
      "calvin klein",
      "tommy hilfiger",
      "ralph lauren",
      "new balance",
      "souvenir",
      "gift shop",
      "pharmacy",
      "cvs",
      "walgreens",
      "target",
      "outlet 購物",
      "伴手禮",
      "名牌",
    ],
  },
  住宿: {
    emoji: "🏨",
    keywords: [
      "住宿",
      "飯店",
      "旅館",
      "hotel",
      "motel",
      "hostel",
      "inn",
      "lodge",
      "airbnb",
      "marriott",
      "hyatt",
      "hilton",
      "homewood",
      "little america",
      "宿",
    ],
  },
  門票: {
    emoji: "🎫",
    keywords: [
      "門票",
      "票",
      "入場",
      "national park",
      "park pass",
      "zion",
      "yellowstone",
      "entrance fee",
      "museum",
      "tour",
      "ticket",
      "attraction",
      "alcatraz",
      "stanford",
      "apple park",
      "ferry",
      "國家公園",
      "入場料",
      "景點",
    ],
  },
  其他: {
    emoji: "📦",
    keywords: [],
  },
};

export function getCategoryEmoji(category: ExpenseCategory): string {
  return CATEGORY_META[category]?.emoji ?? "📦";
}

export function inferCategory(text: string): ExpenseCategory {
  const lower = text.toLowerCase();
  for (const [category, meta] of Object.entries(CATEGORY_META)) {
    if (category === "其他") continue;
    if (meta.keywords.some((kw) => lower.includes(kw))) {
      return category as ExpenseCategory;
    }
  }
  return "其他";
}
